# Generated by Django 6.0.2 on 2026-04-30 17:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_module_enrollment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('WASTE', 'Waste Management'), ('WATER', 'Water Conservation'), ('ENERGY', 'Energy Saving'), ('FOOD', 'Sustainable Food')], default='WASTE', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='eco_score',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.CreateModel(
            name='EcoImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co2_saved', models.FloatField(default=0)),
                ('water_saved', models.FloatField(default=0)),
                ('plastic_reduced', models.FloatField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
